package provider

import (
	"encoding/json"
	"log/slog"
	"net"
	"net/http"

	"github.com/google/uuid"
	"github.com/nhutphuongasasa/loadbalancer/internal/model"
	"github.com/nhutphuongasasa/loadbalancer/internal/registry"
)

type ProviderChannel chan *model.Server

// type IProviderServer interface {
// 	RegisterHTTPHandler() http.Handler
// 	GetProviderChannel() *ProviderChannel
// }

type ProviderServer struct {
	logger              *slog.Logger
	addNewServerChannel ProviderChannel
}

func NewProviderServer(logger *slog.Logger) *ProviderServer {
	return &ProviderServer{
		logger:              logger,
		addNewServerChannel: make(ProviderChannel, 10),
	}
}

/*
*Handler giup thuc hien dnag ky server vao danh sach registry
 */
func (p *ProviderServer) RegisterHTTPHandler() http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
		p.logger.Info("new server register")
		ok, input := p.checkInfo(w, req)
		if !ok {
			return
		}

		resilientTP := p.createResilientTransport(
			input.ServiceName,
			input.InstanceID,
			registry.GlobalBaseTransport,
			p.logger,
		)

		srv := model.NewServer(
			input.InstanceID,
			input.ServiceName,
			input.Host,
			input.Port,
			input.Weight,
			input.Metadata,
			resilientTP,
		)

		p.addNewServerChannel <- srv

		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusCreated)
		json.NewEncoder(w).Encode(map[string]interface{}{
			"status":      "success",
			"message":     "Backend registered successfully",
			"instanceID":  srv.InstanceID,
			"serviceName": srv.ServiceName,
			"host":        srv.Host,
			"port":        srv.Port,
			"weight":      srv.Weight,
			"autoGenerated": map[string]bool{
				"instanceID": input.InstanceID == "",
				"host":       input.Host == "",
				"port":       input.Port == 0,
				"weight":     input.Weight == 0,
			},
		})
	})
}

func (p *ProviderServer) checkInfo(w http.ResponseWriter, req *http.Request) (bool, *model.Input) {
	input := &model.Input{}

	if req.Method != http.MethodPost {
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		return false, nil
	}

	if err := json.NewDecoder(req.Body).Decode(input); err != nil {
		p.logger.Error("Invalid JSON body", "err", err)
		http.Error(w, "Invalid JSON", http.StatusBadRequest)
		return false, nil
	}

	if input.ServiceName == "" {
		http.Error(w, "serviceName is required", http.StatusBadRequest)
		return false, nil
	}

	if input.InstanceID == "" {
		input.InstanceID = uuid.New().String()
	}

	if input.Host == "" {
		host, _, _ := net.SplitHostPort(req.RemoteAddr)
		if host == "" || host == "::1" || host == "127.0.0.1" {
			host = "localhost"
		}
		input.Host = host
	}

	if input.Port <= 0 {
		http.Error(w, "port is required", http.StatusBadRequest)
		input.Port = 8080
	}

	if input.Weight <= 0 {
		input.Weight = 10
	}

	return true, input
}

func (p *ProviderServer) GetProviderChannel() ProviderChannel {
	return p.addNewServerChannel
}
