package provider

import (
	"encoding/json"
	"fmt"
	"log/slog"
	"net"
	"net/http"
	"time"

	"github.com/google/uuid"
	"github.com/nhutphuongasasa/loadbalancer/internal/config"
	"github.com/nhutphuongasasa/loadbalancer/internal/model"
	"github.com/nhutphuongasasa/loadbalancer/internal/registry"
	"github.com/nhutphuongasasa/loadbalancer/internal/resilience"
	circuitBreaker "github.com/nhutphuongasasa/loadbalancer/internal/resilience/circuitbreaker"
	"github.com/nhutphuongasasa/loadbalancer/internal/resilience/retry"
)

type ProviderChannel chan *model.Server

type ProviderServer struct {
	logger              *slog.Logger
	retryCfg            *config.RetryConfig
	cbCfg               *config.CircuitBreakerConfig
	addNewServerChannel ProviderChannel
}

func NewProviderServer(
	retryCfg *config.RetryConfig,
	cbCfg *config.CircuitBreakerConfig,
	logger *slog.Logger,
) *ProviderServer {
	if retryCfg == nil {
		retryCfg = &config.RetryConfig{
			MaxRetries:   3,
			BaseDelay:    200 * time.Millisecond,
			MaxDelay:     3 * time.Second,
			JitterFactor: 0.2,
		}
	}
	if cbCfg == nil {
		cbCfg = config.DefaultCircuitBreakerConfig()
	}
	if logger == nil {
		logger = slog.Default()
	}

	return &ProviderServer{
		logger:              logger,
		retryCfg:            retryCfg,
		cbCfg:               cbCfg,
		addNewServerChannel: make(ProviderChannel, 10),
	}
}

func (p *ProviderServer) RegisterHTTPHandler() http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
		p.logger.Info("new server register")

		ok, input, autoFlags := p.checkInfo(w, req)
		if !ok {
			return
		}

		resilientTP, err := p.createResilientTransport(
			input.ServiceName,
			input.InstanceID,
			registry.GlobalBaseTransport,
		)
		if err != nil {
			p.logger.Error("Failed to create resilient transport",
				slog.String("service", input.ServiceName),
				slog.String("instance", input.InstanceID),
				slog.Any("err", err),
			)
			http.Error(w, "Internal server error", http.StatusInternalServerError)
			return
		}

		srv := model.NewServer(
			input.InstanceID,
			input.ServiceName,
			input.Host,
			input.Port,
			input.Weight,
			input.Metadata,
			resilientTP,
		)

		p.addNewServerChannel <- srv

		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusCreated)
		json.NewEncoder(w).Encode(map[string]interface{}{
			"status":        "success",
			"message":       "Backend registered successfully",
			"instanceID":    srv.InstanceID,
			"serviceName":   srv.ServiceName,
			"host":          srv.Host,
			"port":          srv.Port,
			"weight":        srv.Weight,
			"autoGenerated": autoFlags,
		})
	})
}

// createResilientTransport dùng config từ struct — không nhận params thừa.
// Trả về error nếu circuit breaker init fail (invalid config).
func (p *ProviderServer) createResilientTransport(
	serviceName, instanceID string,
	baseTransport http.RoundTripper,
) (http.RoundTripper, error) {
	breakerName := fmt.Sprintf("cb-%s-%s", serviceName, instanceID)

	breaker, err := circuitBreaker.NewSonyGoBreaker(breakerName, p.cbCfg, p.logger)
	if err != nil {
		return nil, fmt.Errorf("circuit breaker %q init failed: %w", breakerName, err)
	}

	retryPol := retry.NewExponentialRetry(p.retryCfg, p.logger)

	return resilience.NewResilientTransport(
		baseTransport,
		breaker,
		retryPol,
		p.logger,
	), nil
}

// checkInfo validate và normalize input.
// Trả về (ok, input, autoGenerated map) để caller biết field nào được tự sinh.
func (p *ProviderServer) checkInfo(w http.ResponseWriter, req *http.Request) (bool, *model.Input, map[string]bool) {
	input := &model.Input{}
	auto := map[string]bool{
		"instanceID": false,
		"host":       false,
		"weight":     false,
	}

	if req.Method != http.MethodPost {
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		return false, nil, nil
	}

	if err := json.NewDecoder(req.Body).Decode(input); err != nil {
		p.logger.Error("Invalid JSON body", "err", err)
		http.Error(w, "Invalid JSON", http.StatusBadRequest)
		return false, nil, nil
	}

	if input.ServiceName == "" {
		http.Error(w, "serviceName is required", http.StatusBadRequest)
		return false, nil, nil
	}

	if input.InstanceID == "" {
		input.InstanceID = uuid.New().String()
		auto["instanceID"] = true
	}

	if input.Host == "" {
		host, _, _ := net.SplitHostPort(req.RemoteAddr)
		if host == "" || host == "::1" || host == "127.0.0.1" {
			host = "localhost"
		}
		input.Host = host
		auto["host"] = true
	}

	if input.Port <= 0 {
		http.Error(w, "port is required", http.StatusBadRequest)
		return false, nil, nil
	}

	if input.Weight <= 0 {
		input.Weight = 10
		auto["weight"] = true
	}

	return true, input, auto
}

func (p *ProviderServer) GetProviderChannel() ProviderChannel {
	return p.addNewServerChannel
}
